sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1375366174
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tH3NoYPtFM6bpVfcPmL
    access-key-secret: 3MHvpAgp06CWUqdvPCm18Mz9PbMvTe
    bucket-name: sky-take-out-itcast1375

  redis:
    host: localhost
    port: 6379
    database: 0

  wechat:
    appid: wx3fd194154863fa97
    secret: ff9396eb6ddad60b0e5d5e7eaf981fae